### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [snoyberg/mono-traversable#199]
The current master fails to build with GHC 9.2 since `Option` was removed from `base`.
```
$ cabal build --allow-newer=split:base

Build profile: -w ghc-9.2.0.20210806 -O1
In order, the following will be built (use -v for more details):
 - split-0.2.3.4 (lib) (requires build)
 - vector-algorithms-0.8.0.4 (lib) (requires build)
 - mono-traversable-1.0.15.2 (lib) (first run)

src/Data/MonoTraversable.hs:97:35: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
97 | import Data.Semigroup (Semigroup, Option (..), Arg)
   |                                   ^^^^^^^^^^^
```

**Comment by snoyberg** [comment]
Interested in a PR with some added CPP-fu to make this work? I'm not set up with GHC 9.2 myself to play with this.

**Comment by snoyberg** [comment]
Given GHC's aggressive (overly, IMO) release policy and tendency to break things regularly, I have no intention of maintaining lots of backwards compat anymore, it's simply too large a maintenance burden. I set my lower bounds in line with what the CI jobs cover. Removing the CPP is best.

**Comment by andreasabel** [comment]
> I set my lower bounds in line with what the CI jobs cover.

I agree that all supported GHC versions should also be covered by CI.

Out of curiosity, was there a reason to restrict CI to >= 8.8?

**Comment by snoyberg** [comment]
I don't remember offhand. 8.8 is reasonable since it fits the 3 version policy. But I think one of the packages in this repo had trouble on older GHCs.

**Comment by andreasabel** [comment]
GHC's nervosity is spreading to the whole Haskell ecosystem by requiring constant updates.  However, it seems to me if packages close to the root of the dependency tree are supporting a wide range of GHC versions, the oscillation caused by GHC could be damped a bit, making the ripples smaller rather than emphasizing them.

This is why I am on a _5-year_ policy rather than a _3 version_ policy.  I don't know who came up with the 3 version policy but it seems to me more psychological than rational. _Omnes trium perfectum_, "three strikes and you are out", 3 attempts on your PIN or password---it seems than humans pick the number 3 when it comes to a "sufficient quantity" (esp. in interaction).  I find nothing rational about only getting 3 attempts on my PINs, I find this rather highly superstitious.

Anyway, I should stop my rant against the number 3.  I completely sympathize with your frustration of the maintenance burden GHC places on all of us, and I also think we are burning a lot of time that could be used more creatively.

So, instead of just talking, here is a PR that rips out most of the `#if`s from this repo: #200.

**Comment by andreasabel** [comment]
Compilation fix for 9.2 at PR #201.
