### PR TITLE
Fix #199: support GHC 9.2 (base 4.16) by putting Option under #if

### LINKED ISSUE #199: Support GHC 9.2
The current master fails to build with GHC 9.2 since `Option` was removed from `base`.
```
$ cabal build --allow-newer=split:base

Build profile: -w ghc-9.2.0.20210806 -O1
In order, the following will be built (use -v for more details):
 - split-0.2.3.4 (lib) (requires build)
 - vector-algorithms-0.8.0.4 (lib) (requires build)
 - mono-traversable-1.0.15.2 (lib) (first run)

src/Data/MonoTraversable.hs:97:35: error:
    Module ‘Data.Semigroup’ does not export ‘Option(..)’
   |
97 | import Data.Semigroup (Semigroup, Option (..), Arg)
   |                                   ^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #199: support GHC 9.2 (base 4.16) by putting Option under #if

In base-4.16, Option was removed.

Bump version to 1.0.15.3.

I tested manually that this PR compiles with GHC 8.8 - 9.2.1-rc1.

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]
Thanks!

**Comment by parsonsmatt** [comment]
any chance we could get a Hackage release on this?

**Comment by parsonsmatt** [comment]
Oh, very weird. We're depending on this commit for `mutable-containers`, which was last uploaded in 2018. I wonder what we're *actually* depending on? 🤔
