### ISSUE TITLE
The IO action ‘main’ is not defined in module ‘Main’ (GHC 9.0.1)

### ISSUE THREAD

**Issue by pjones** [snoyberg/mono-traversable#192]
mono-traversable fails to build with GHC 9.0.1:

```
test/main.hs:1:1: error:
    The IO action ‘main’ is not defined in module ‘Main’
  |
1 | import Spec (main)
  | ^
```

Is it okay to rename `Spec.hs` to `Main.hs` (also changing its module name) and remove `main.hs`?

**Comment by snoyberg** [comment]
No objection, as long as it doesn't break previous GHC releases.

**Comment by yaitskov** [comment]
why there is no release for last 3 years?

**Comment by andreasabel** [comment]
@yaitskov There has been a release for Christmas 2019 which is less than 2 years ago!

**Comment by snoyberg** [comment]
Just forgot to hit upload after merging #193. New release with these changes is on Hackage now.
