### ISSUE TITLE
`classy-prelude` does not build with `time >= 1.10`

### ISSUE THREAD

**Issue by GeorgeCo** [snoyberg/mono-traversable#204]
classy-prelude does not build on ghc 9.2.1:

```
 ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
bash-3.2$ cabal install classy-prelude
...
Building library for classy-prelude-1.5.0..
[1 of 2] Compiling ClassyPrelude    ( src/ClassyPrelude.hs, dist/build/ClassyPrelude.o, dist/build/ClassyPrelude.dyn_o )

src/ClassyPrelude.hs:193:7: error:
    Module ‘Data.Time’ does not export ‘parseTime’
    |
193 |     , parseTime
    |       ^^^^^^^^^
```

**Comment by andreasabel** [comment]
According to https://hackage.haskell.org/package/time-1.12/changelog, `parseTime` was removed in `time-1.10`.
This succeeds:
```
cabal install classy-prelude --constraint='time<1.10'
```
I revised 1.5.0 accordingly, see https://hackage.haskell.org/package/classy-prelude-1.5.0/revisions/.
@GeorgeCo Please try again (after `cabal update`!).
